name: CI – Build & Publish Docker Image

on:
  push:
    branches:
      - staging

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    services:
      db-marlin:
        image: timescale/timescaledb:pg17
        ports:
          - 6000:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: sql
          POSTGRES_DB: marlin
        options: >-
          --health-cmd="pg_isready -U user -d marlin"
          --health-interval=3s
          --health-timeout=3s
          --health-retries=30

    env:
      IMAGE_NAME: marlin_backend_beta
      REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      DEPLOY_KEY: ${{ secrets.MARLIN_DEPLOY_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"
          cache: 'maven'

      - name: Start Docker Compose services
        run: docker compose up -d

      - name: Build with Maven
        run: mvn clean package

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.SERVER_IP }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.DEPLOY_KEY }}
          script: |
            sudo systemctl stop marlin-test.service
            docker pull ${{ env.REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            sudo systemctl start marlin-test.service