name: CI – Build & Publish Docker Image

on:
  push:
    branches:
      - release

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

#    env:
#      IMAGE_NAME: backend
#      REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
#      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
#      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "21"

      - name: Build with Maven
        run: mvn clean package

#      - name: Login to container registry
#        uses: docker/login-action@v3
#        with:
#          registry: ${{ env.REGISTRY_URL }}
#          username: ${{ env.REGISTRY_USERNAME }}
#          password: ${{ env.REGISTRY_TOKEN }}
#
#      - name: Build & push Docker image
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: |
#            ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
#            ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:latest
#          cache-from: type=registry,ref=${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:latest
#          cache-to: type=inline
